### PR TITLE
Response next previous mark

### PR DESCRIPTION
**Pull request by markphelps**
Refactoring next/previous
* removed rest/utils.rb
* created rest/response.rb to act as response builder
* changed signature of response.rb to remove summary and add connection

### CODE REVIEW

**Comment by markphelps** [comment]
@allcentury @johaywood @jaysonlarin what are your thoughts?

**Comment by allcentury** [comment]
I like the changes in here.  What will the API be to use `next` and `previous`?  I can see it in the object as:

```
[11] pry(main)> client.get_fitnesses.summary
=> #<Validic::Summary:0x007f9d2430a980
 @end_date="2016-01-27T23:59:59+00:00",
 @limit=100,
 @message="Ok",
 @next="https://api.validic.com/v1/organizations/our_id/fitness?access_token=our_token&page=2",
 @offset=0,
 @previous=nil,
 @results=110,
 @start_date="2016-01-25T00:00:00+00:00",
 @status=200,
 @timestamp=nil>
```

**Comment by markphelps** [comment]
@allcentury see https://github.com/Validic/validic/blob/response_next_previous/spec%2Fvalidic%2Fresponse_spec.rb#L21 for an example usage

**Comment by allcentury** [comment]
So in order to get all the records from a paginated response we'd encourage them to do something like this?

```ruby
client = Validic::Client.new(organization_id: 'our_id', access_token: 'token')

# arg: client
# return: array
def get_all_fitness_records(client)
  total_records = []
  current_resp = client.get_fitnesses
  loop do
    break if current_resp.nil?
    total_records += current_resp.records
    current_resp = current_resp.next
  end
  total_records
end

puts get_all_fitness_records(client).size
```

You can obviously make that handle all the objects instead of just fitness but this was just an example.

**Comment by markphelps** [comment]
correct. just like paging 'by hand' using a rest client

On Tue, Jan 26, 2016 at 10:03 AM, Anthony Ross <notifications@github.com>
wrote:

> So in order to get all the records from a paginated response we'd
> encourage them to do something like this?
>
> client = Validic::Client.new(organization_id: 'our_id', access_token: 'token')
> # arg: client# return: arraydef get_all_fitness_records(client)
>   total_records = []
>   current_resp = client.get_fitnesses
>   loop do
>     break if current_resp.nil?
>     total_records += current_resp.records
>     current_resp = current_resp.next
>   end
>   total_recordsend
>
> puts get_all_fitness_records(client).size
>
> You can obviously make that handle all the objects instead of just fitness
> but this was just an example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Validic/validic/pull/33#issuecomment-175062874>.
>



-- 
Mark Phelps
Senior Software Engineer
http://validic.com

**Comment by allcentury** [comment]
Alright - I think your changes look good.

**Pull request merged**
